# Change these first
owner: jeason81 # Your GitHub username
repo: upptime # Your Github repository name

# Add your sites here
sites:
  - name: Google
    url: https://www.google.com
  - name: Ironbank
    url: https://ironbank.dso.mil
    assignees:
      - jeason81
    maxResponseTime: 5000
  - name: Repo1
    url: https://repo1.dso.mil/api/v4/version
    expectedStatusCodes:
      - 200
      - 201
      - 401
    maxResponseTime: 5000
    assignees:
      - jeason81
  - name: Registry1
    url: https://registry1.dso.mil
    expectedStatusCodes:
      - 200


status-website:
#   # Add your custom domain below, or remove the next line if you don't have a domain
#   cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime
  logoUrl: https://repo1.dso.mil/uploads/-/system/group/avatar/40/Iron_Bank_Logo_small.png?width=38
  name: Ironbank
  introTitle: PlatformOne
  introMessage: Ironbank status page
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO